### ISSUE TITLE
Not working :)

### ISSUE THREAD

**Issue by raiftekin** [SECTN/FATBOT-youtube-viewer-bot#1]
![Screenshot_20190505-160439](https://user-images.githubusercontent.com/50047969/57194444-b453c880-6f4f-11e9-834d-203a61289787.png)
Https: // whether or not two types of not working .
I'm interested in details

**Comment by lieinside** [comment]
how can fix this ?

Enter YouTube URL : https://www.youtube.com/watch?v=oTrzee79sOU
Traceback (most recent call last):
  File "FATBOT.py", line 13, in <module>
    url = input("Enter YouTube URL : ")
  File "<string>", line 1
    https://www.youtube.com/watch?v=oTrzee79sOU
         ^
SyntaxError: invalid syntax

**Comment by trikyas** [comment]
Try adding ' ' around the URL and also the browser name ...

You're welcome

<img width="889" alt="Screen Shot 2019-08-09 at 11 02 33 pm" src="https://user-images.githubusercontent.com/4310786/62780825-e9952700-baf9-11e9-9a48-924c6eecc707.png">
